# Generated by Django 4.0.4 on 2022-06-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indumentarias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='indumentaria'),
        ),
    ]
