# Generated by Django 4.0.4 on 2022-06-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike', '0002_alter_indumentarias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indumentarias',
            name='imagen',
            field=models.ImageField(null=True, upload_to='indumentaria'),
        ),
    ]
