# Generated by Django 4.0.4 on 2022-06-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorios',
            name='imagen',
            field=models.ImageField(null=True, upload_to='accesorio'),
        ),
        migrations.AddField(
            model_name='calzados',
            name='imagen',
            field=models.ImageField(null=True, upload_to='calzado'),
        ),
    ]
